export default {
  "+ Add Horizontal Giude":"+ Add Horizontal Giude",
  "+ Add Vertical Giude":"+ Add Vertical Giude",
  "2D View": "2D View",
  "3D First Person": "3D First Person",
  "3D View": "3D View",
  "altitude": "altitude",
  "Altitude": "Altitude",
  "Areas":"Areas",
  "Cancel": "Cancel",
  "Catalog" : "Catalog",
  "Chain selected Elements to Group":"Chain selected Elements to Group",
  "Circular":"Circular",
  "color":"color",
  "Configure layer": "Configure layer",
  "Configure project": "Configure project",
  "Confirm": "Confirm",
  "Copy":"Copy",
  "Delete group and all Elements":"Delete group and all Elements",
  "Delete layer": "Delete layer",
  "Delete": "Delete",
  "Elements on layer {0}": "Elements on layer {0}",
  "Elements":"Elements",
  "Get Screenshot" : "Get Screenshot",
  "Group [{0}]":"Group [{0}]",
  "Group's Barycenter":"Group's Barycenter",
  "Group's Elements":"Group's Elements",
  "Groups":"Groups",
  "Guides":"Guides",
  "Height": "Height",
  "Holes":"Holes",
  "Horizontal":"Horizontal",
  "Items":"Items",
  "Last Selected":"Last Selected",
  "Layer config": "Layer config",
  "Layer":"Layer",
  "Layers": "Layers",
  "Length":"Length",
  "Lines":"Lines",
  "Load project": "Load project",
  "Mouse X Coordinate":"Mouse X Coordinate",
  "Mouse Y Coordinate":"Mouse Y Coordinate",
  "Name": "Name",
  "New Empty Group":"New Empty Group",
  "New Group from selected":"New Group from selected",
  "New layer": "New layer",
  "New project": "New project",
  "opacity": "opacity",
  "Open catalog": "Open catalog",
  "order": "order",
  "Pan": "Pan",
  "Paste":"Paste",
  "Project config": "Project config",
  "Properties: [{0}] {1}": "Properties: [{0}] {1}",
  "Prototype":"Prototype",
  "Reset": "Reset",
  "Rotation" : "Rotation",
  "Save project": "Save project",
  "Save": "Save",
  "Scene Zoom Level":"Scene Zoom Level",
  "Search Element":"Search Element",
  "Snap to Grid":"Snap to Grid",
  "Snap to Guide":"Snap to Guide",
  "Snap to Line":"Snap to Line",
  "Snap to Point":"Snap to Point",
  "Snap to Segment":"Snap to Segment",
  "Orthogonal": "Orthogonal",
  "texture":"texture",
  "thickness":"thickness",
  "Toggle Group Visibility":"Toggle Group Visibility",
  "Un-chain all Group\'s Elements and remove Group":"Un-chain all Group\'s Elements and remove Group",
  "Un-chain Element from Group":"Un-chain Element from Group",
  "Undo (CTRL-Z)": "Undo (CTRL-Z)",
  "Unselect": "Unselect",
  "Vertical":"Vertical",
  "width": "width",
  "Would you want to start a new Project?": "Would you want to start a new Project?",
  "Zoom in": "Zoom in",
  "Zoom out": "Zoom out",
  "Export project": "Export project",
  "Default Wall Height": "Default Wall Height",
  "Default Wall Width": "Default Wall Width",
  "Thermal Regulations": "Thermal Regulations",
  "Current thermal regulations": "Current thermal regulations",
  "Future thermal regulations": "Future thermal regulations",
  "Region": "Region",
  "Commune": "Commune",
  "Type of grouping": "Type of grouping",
  "Isolated Building": "Isolated Building",
  "Vertically Paired Building": "Vertically Paired Building",
  "Horizontal Paired Building": "Horizontal Paired Building",
  "Continuous Building": "Continuous Building",
  "Collective Building": "Collective Building",
  "Number of floors": "Number of floors",
  "First floor type": "First floor type",
  "Ventilated": "Ventilated",
  "Radier": "Radier",
  "Number of square meters of the building": "Number of square meters of the building (m2)",
  "Thermal Requirement": "Thermal Requirement",
  "Fire Resistance Requirement": "Fire Resistance Requirement",
  "Acoustic Requirement": "Acoustic Requirement",
  "Aerial acoustic requirement": "Aerial acoustic requirement",
  "Acoustic impact requirement": "Acoustic impact requirement",
  "wall": "wall",
  "separator": "separator",
  "door": "door",
  "window": "window",
  "gate": "gate",
  "PERIMETER WALL": "PERIMETER WALL",
  "INTERIOR  WALL": "INTERIOR  WALL",
  "DIVIDING  WALL": "DIVIDING  WALL"

};
