export default {
  "+ Add Horizontal Giude":"+ Agregar Guia Horizontal",
  "+ Add Vertical Giude":"+ Agregar Guia Vertical",
  "2D View": "Vista 2D",
  "3D First Person": "3D First Person",
  "3D View": "3D View",
  "altitude": "altitud",
  "Altitude": "Altitud",
  "Areas":"Areas",
  "Cancel": "Cancelar",
  "Catalog" : "Catalogo",
  "Chain selected Elements to Group":"Convertir elementos en Grupo",
  "Circular":"Circular",
  "color":"color",
  "Configure layer": "Configuracion de layer",
  "Configure project": "Configuracion de projecto",
  "Confirm": "Confirmar",
  "Copy":"Copiar",
  "Delete group and all Elements":"Borrar grupo y todos los Elementos",
  "Delete layer": "Borrar layer",
  "Delete": "Borrar",
  "Elements on layer {0}": "Elementos en layer {0}",
  "Elements":"Elementos",
  "Get Screenshot" : "Capturar Pantalla",
  "Group [{0}]":"Grupo [{0}]",
  "Group's Barycenter":"Group's Barycenter",
  "Group's Elements":"Elementos de Grupo",
  "Groups":"Grupos",
  "Guides":"Guias",
  "Height": "Altura",
  "Canvas Height": "Altura de la lona",
  "Holes":"Vanos",
  "Horizontal":"Horizontal",
  "Items":"Items",
  "Last Selected":"Ultimo Seleccionado",
  "Layer config": "configuracion de layer",
  "Layer":"Layer",
  "Layers": "Layers",
  "Length":"Largo",
  "Lines":"Lineas",
  "Load project": "Cargar Proyecto",
  "Mouse X Coordinate":"Coordenadas de Mouse X ",
  "Mouse Y Coordinate":"Coordenadas de Mouse Y ",
  "Name": "Nombre",
  "New Empty Group":"Nuevo grupo sin Elementos",
  "New Group from selected":"Nuevo grupo de Elementos",
  "New layer": "Nueva layer",
  "New project": "Nuevo proyecto",
  "opacity": "Opacidad",
  "Open catalog": "Abrir catalogo",
  "order": "Orden",
  "Pan": "Pan",
  "Paste":"Pegar",
  "Project config": "Configuracion de Proyecto",
  "Properties: [{0}] {1}": "Propiedades: [{0}] {1}",
  "Prototype":"Prototipo",
  "Reset": "Reset",
  "Rotation" : "Rotar",
  "Save project": "Guardar Proyecto",
  "Save": "Guardar",
  "Scene Zoom Level":"Nivel de zoom a escena",
  "Search Element":"Buscar Elemento",
  "Snap to Grid":"Snap a Ejes",
  "Snap to Guide":"Snap a Guias",
  "Snap to Line":"Snap a Lineas",
  "Snap to Point":"Snap a Puntos",
  "Snap to Segment":"Snap a Segmentos",
  "Orthogonal": "Ortogonal",
  "texture":"textura",
  "thickness":"Espesor",
  "Toggle Group Visibility":"Activar-Desactivar Visibilidad en Grupos",
  "Un-chain all Group\'s Elements and remove Group":"Un-chain all Group\'s Elements and remove Group",
  "Un-chain Element from Group":"Un-chain Element from Group",
  "Undo (CTRL-Z)": "Deshacer (CTRL-Z)",
  "Unselect": "Deseleccion",
  "Vertical":"Vertical",
  "width": "ancho",
  "Would you want to start a new Project?": "Le gustaria comenzar un nuevo proyecto?",
  "Zoom in": "Zoom in",
  "Zoom out": "Zoom out",
  "Export project": "Proyecto de exportación",
  "Default Wall Height": "Altura de muro por default",
  "Default Wall Width": "Ancho de pared predeterminado",
  "Thermal Regulations": "Normativa térmica",
  "Current thermal regulations": "Normativa térmica vigente",
  "Future thermal regulations": "Normativa térmica futura",
  "Region": "Región",
  "Commune": "Comuna",
  "Type of grouping": "Tipo de agrupación",
  "Isolated Building": "Edificación Aislada",
  "Vertically Paired Building": "Edificación Pareada Verticalmente",
  "Horizontal Paired Building": "Edificación Pareada Horizontalmente",
  "Continuous Building": "Edificación Continua",
  "Collective Building": "Edificación Colectiva",
  "Number of floors": "Cantidad de pisos",
  "First floor type": "Tipo de Primer piso",
  "Ventilated": "Ventilado",
  "Radier": "Radier",
  "Number of square meters of the building": "Cantidad de Metros cuadrado del edificio (m2)",
  "Thermal Requirement": "Requerimientos Térmico",
  "Fire Resistance Requirement": "Requerimiento de resistencia al fuego",
  "Acoustic Requirement": "Requerimiento Acústico",
  "Aerial acoustic requirement": "Requerimiento acústico aéreo",
  "Acoustic impact requirement": "Requerimiento acústico de impacto",
  "wall": "muro",
  "separator": "separador",
  "door": "puerta",
  "window": "ventana",
  "gate": "puerta",
  "PERIMETER WALL": "MURO PERÍMETRAL",
  "INTERIOR  WALL": "MURO INTERIOR",
  "DIVIDING  WALL": "MURO DIVISORIO",
  'areaType':'Tipo de área'
};
